availability_domain  = "your_availability_domain"
compartment_id       = "your_compartment_ocid"
instance_shape       = "VM.Standard.A1.Flex"
subnet_id            = "your_subnet_ocid"
image_id             = "your_image_ocid"
ssh_public_key_path  = "~/.ssh/id_rsa.pub"